ipaserver_domain: mobile.bk.lab
ipaserver_realm: MOBILE.BK.LAB
ipadm_password: "{{ lab_ipa_dm_password }}"
ipaserver_setup_dns: true
ipaserver_no_host_dns: true
ipaserver_auto_reverse: true
ipaserver_auto_forwarders: true
