---
- name: Install basic idm client in lab environment
  hosts: satellite
  become: false
  vars_files:
    - ../vault.yml
  roles:
    - role: redhat.rhel_system_roles.timesync
    - role: redhat.rhel_idm.ipaclient
      state: present
