---
- name: Install basic idm client in lab environment
  hosts: all,!ipaservers,!ipareplicas,!satellite,!lab
  become: false
  vars_files:
    - ../vault.yml
  pre_tasks:
    - name: Install satellite ca package
      ansible.builtin.dnf:
        name: 'http://192.168.124.7/pub/katello-ca-consumer-latest.noarch.rpm'
        disable_gpg_check: true
        state: present
    - name: Register system with Satellite
      community.general.redhat_subscription:
        activationkey: "{{ lab_satellite_activationkey }}"
        org_id: "{{ lab_satellite_organization }}"
    - name: Install all updates
      ansible.builtin.dnf:
        name: "*"
        state: latest
    - name: Reboot after updates
      ansible.builtin.reboot:
        msg: "Rebooting after updates"
  roles:
    - role: redhat.rhel_system_roles.timesync
    - role: redhat.rhel_idm.ipaclient
      state: present # noqa: var-naming[no-role-prefix]
