---
- name: Install satellite
  hosts: satellite
  become: false
  vars_files:
    - ../vault.yml
  pre_tasks:
    - name: Unregister from RHSM
      community.general.redhat_subscription:
        state: absent
    - name: Register system with RHSM
      community.general.redhat_subscription:
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        pool_ids: "{{ lab_satellite_subscription_pool }}"
    - name: Disable all rhsm repositories
      community.general.rhsm_repository:
        name: "*"
        state: disabled
    - name: Enable satellite repositories
      community.general.rhsm_repository:
        name: "{{ lab_satellite_repositories }}"
        state: enabled
    - name: Enable the satellite appstream
      ansible.builtin.shell:
        cmd: 'dnf -y module enable satellite:el8'
    - name: Update all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
  roles:
    - role: redhat.rhel_system_roles.timesync
    - role: redhat.satellite_operations.installer
  tasks:
    - name: Enable RH-Satellite-6 Firewalld Service
      ansible.posix.firewalld:
        service: RH-Satellite-6
        permanent: true
        state: enabled
        immediate: true
