---
- name: Install basic idm client in lab environment
  hosts: aap,testaap
  become: true
  vars_files:
    - ../vault.yml
  pre_tasks:
    - name: Install all updates
      ansible.builtin.dnf:
        name: "*"
        state: latest
    - name: Reboot after updates
      ansible.builtin.reboot:
        msg: "Rebooting after updates"
  roles:
    - role: redhat.rhel_system_roles.timesync
    - role: redhat.rhel_idm.ipaclient
      state: present
