---
- name: Install OSBuild Server in Lab environment
  hosts: utility
  become: true
  vars_files:
    - ../vault.yml
  pre_tasks:
    - name: Install all updates
      ansible.builtin.dnf:
        name: "*"
        state: latest
    - name: Reboot after updates
      ansible.builtin.reboot:
        msg: "Rebooting after updates"
  roles:
    - name: infra.osbuild.setup_server